name: Tests
on: push
jobs:
  default:
    runs-on: ubuntu-latest
    container:
      image: php:7.4-cli
    steps:
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies with composer
        uses: php-actions/composer@v6

      - name: Run tests with phpunit/phpunit
        uses: php-actions/phpunit@v3
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-clover=coverage.xml --log-junit=testresults.xml
          php_version: "7.4"
